spring:
  main:
    banner-mode: off
    web-application-type: none

  datasource:
    url: jdbc:derby:directory:drd-db;create=true
    username: drd
    
#  flyway:
#    enabled: true
#    locations: "classpath:db/migration"
